version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ashok-ws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xh6uwn1189iv"
s3_prefix = "ashok-ws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"ashokdydbtable\""
image_repositories = []
